import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiGo,
  SiRust,
  SiPython,
  SiCplusplus,
  SiNestjs,
  SiExpress,
  SiReact,
  SiVuedotjs,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiDocker,
  SiLinux,
  SiArduino,
  SiMqtt,
  SiNginx,
  SiKubernetes,
  SiGooglecloud,
  SiTypescript,
  SiNuxtdotjs,
  SiMysql,
  SiSqlite,
  SiGithubactions,
  SiNodedotjs,
  SiAmazonwebservices,
  SiActix,
  SiRocksdb,
  SiEspressif,
  SiGrafana,
  SiNodered,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaJava } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  golang: SiGo,
  rust: SiRust,
  python: SiPython,
  cplusplus: SiCplusplus,
  nestjs: SiNestjs,
  express: SiExpress,
  react: SiReact,
  vue: SiVuedotjs,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  redis: SiRedis,
  docker: SiDocker,
  linux: SiLinux,
  arduino: SiArduino,
  mqtt: SiMqtt,
  gin: SiGo,
  nginx: SiNginx,
  kubernetes: SiKubernetes,
  googlecloud: SiGooglecloud,
  java: FaJava,
  typescript: SiTypescript,
  hapi: SiNodedotjs,
  nuxt: SiNuxtdotjs,
  mysql: SiMysql,
  sqlite: SiSqlite,
  rocksdb: SiRocksdb,
  githubactions: SiGithubactions,
  esp32: SiEspressif,
  emqx: SiMqtt,
  grafana: SiGrafana,
  nodered: SiNodered,
  aws: SiAmazonwebservices,
  actix: SiActix,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
