-- Drop added columns from works_metadata
ALTER TABLE works_metadata DROP COLUMN title;
ALTER TABLE works_metadata DROP COLUMN content;
ALTER TABLE works_metadata DROP COLUMN summary;
ALTER TABLE works_metadata DROP COLUMN project_name;
ALTER TABLE works_metadata DROP COLUMN images;
ALTER TABLE works_metadata DROP COLUMN link;
ALTER TABLE works_metadata DROP COLUMN repository;
ALTER TABLE works_metadata DROP COLUMN team;
ALTER TABLE works_metadata DROP COLUMN published_at;

-- Drop added columns from blogs_metadata
ALTER TABLE blogs_metadata DROP COLUMN title;
ALTER TABLE blogs_metadata DROP COLUMN content;
ALTER TABLE blogs_metadata DROP COLUMN summary;
ALTER TABLE blogs_metadata DROP COLUMN blog_title;
ALTER TABLE blogs_metadata DROP COLUMN images;
ALTER TABLE blogs_metadata DROP COLUMN source;
ALTER TABLE blogs_metadata DROP COLUMN published_at;
