<script lang="ts">
  import { Github, Linkedin, Mail, MapPin } from 'lucide-svelte';
  import { experiences, projects } from '../lib/data';
  import { navigate } from '../lib/router';
  import ProjectCard from '../lib/ui/ProjectCard.svelte';
  import SectionHeader from '../lib/ui/SectionHeader.svelte';
</script>
<main class="mx-auto max-w-7xl px-4 lg:px-8"><section class="grid gap-10 py-14 lg:grid-cols-[1.05fr_.95fr] lg:gap-20 lg:py-16"><div><p class="text-[10px] font-semibold uppercase tracking-[0.24em] text-base-content/55">Software Engineer · Backend · AI · IoT</p><h1 class="mt-5 text-5xl font-semibold tracking-tight md:text-6xl">Alex Morgan</h1><p class="mt-3 text-4xl font-light leading-tight text-base-content/65 md:text-5xl">Building reliable systems<br/>for complex problems.</p><p class="mt-5 max-w-xl leading-7 text-base-content/60">A software engineer working across backend architecture, intelligent systems, cloud infrastructure, and connected devices.</p><div class="mt-7 flex flex-wrap gap-3"><a class="btn btn-neutral rounded-none px-6" href="/projects" on:click={(e)=>navigate(e,'/projects')}>View Projects →</a><a class="btn btn-outline rounded-none px-6" href="mailto:hello@example.com">Contact</a></div><div class="mt-7 flex flex-wrap gap-6 border-t border-base-300 pt-4 text-xs text-base-content/60"><span class="flex items-center gap-2"><MapPin size={14}/>Jakarta, Indonesia</span><span class="flex items-center gap-2"><span class="status status-success"></span>Available for selected opportunities</span></div><div class="mt-5 flex gap-5 text-xs"><a class="flex items-center gap-2" href="https://github.com"><Github size={15}/>GitHub</a><a class="flex items-center gap-2" href="https://linkedin.com"><Linkedin size={15}/>LinkedIn</a><a class="flex items-center gap-2" href="mailto:hello@example.com"><Mail size={15}/>Email</a></div></div><div><img class="aspect-[1.38] w-full bg-base-200 object-cover" src="/images/profile.svg" alt="Alex Morgan"/><blockquote class="ml-auto mt-5 w-fit border-l border-base-300 pl-4 text-right text-sm text-base-content/55">“Better systems create<br/>more possibilities.”</blockquote></div></section>
<section class="border-t border-base-300 py-8"><SectionHeader eyebrow="Selected experience" action="View full experience" href="/experience"/>{#each experiences.slice(0,3) as item}<div class="grid gap-3 border-b border-base-300 py-5 md:grid-cols-[150px_1fr_1.4fr]"><p class="text-xs text-base-content/50">{item.year}</p><div><h3 class="font-semibold">{item.role}</h3><p class="text-xs text-base-content/50">{item.company}</p></div><p class="text-sm leading-6 text-base-content/55">{item.summary}</p></div>{/each}</section>
<section class="border-t border-base-300 py-8"><SectionHeader eyebrow="Selected projects" action="View all projects" href="/projects"/><div class="grid gap-8 md:grid-cols-2">{#each projects.slice(0,4) as project}<ProjectCard {project}/>{/each}</div></section>
<section class="grid gap-8 border-t border-base-300 py-9 md:grid-cols-2"><div><p class="text-[10px] font-semibold uppercase tracking-[0.22em] text-base-content/55">About</p><h2 class="mt-4 text-3xl font-light leading-tight">I care about software that<br/>remains understandable<br/>after it grows.</h2></div><div class="self-end text-sm leading-6 text-base-content/60"><p>I enjoy building systems at the intersection of backend infrastructure, intelligent systems, and connected devices. I value clarity, long-term thinking, and maintainable solutions.</p><a class="link mt-4 inline-block" href="/about" on:click={(e)=>navigate(e,'/about')}>More about me →</a></div></section></main>
